# -*- coding: utf-8 -*-
"""iPhone Sales Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m-prMQDUlUqQC0hc_DShnAyo2zTlTqbT

# ***iPhone Sales Analysis using Python***

Now let’s import the necessary Python libraries and the dataset to get started with the task of iPhone sales analysis:
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

data = pd.read_csv("/content/apple_products.csv")
print(data.head())

"""Before moving forward, let’s have a quick look at whether this dataset contains any null values or not:

"""

print(data.isnull().sum())

"""The dataset doesn’t have any null values. Now, let’s have a look at the descriptive statistics of the data:"""

print(data.describe())

"""iPhone Sales Analysis in India🇮🇳

Now I will create a new dataframe by storing all the data about the top 10 highest-rated iPhones in India on Flipkart. It will help in understanding what kind of iPhones are liked the most in India:
"""

highest_rated = data.sort_values(by=["Star Rating"],
                                 ascending=False)
highest_rated = highest_rated.head(10)
print(highest_rated['Product Name'])

"""According to the above data, below are the top 5 most liked iPhones in India:



*   APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)
*   APPLE iPhone 11 Pro Max (Space Grey, 64 GB)
*   APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)
*   APPLE iPhone 11 Pro Max (Gold, 64 GB)
*   APPLE iPhone 11 Pro Max (Gold, 256 GB)

Now let’s have a look at the number of ratings of the highest-rated iPhones on Flipkart:
"""

iphones = highest_rated["Product Name"].value_counts()
label = iphones.index
counts = highest_rated["Number Of Ratings"]
figure = px.bar(highest_rated, x=label,
                y = counts,
            title="Number of Ratings of Highest Rated iPhones")
figure.show()

"""According to the above bar graph, APPLE iPhone 8 Plus (Gold, 64 GB) has the most ratings on Flipkart. Now let’s have a look at the number of reviews of the highest-rated iPhones on Flipkart:"""

iphones = highest_rated["Product Name"].value_counts()
label = iphones.index
counts = highest_rated["Number Of Reviews"]
figure = px.bar(highest_rated, x=label,
                y = counts,
            title="Number of Reviews of Highest Rated iPhones")
figure.show()

"""APPLE iPhone 8 Plus (Gold, 64 GB) is also leading in the highest number of reviews on Flipkart among the highest-rated iPhones in India. Now let’s have a look at the relationship between the sale price of iPhones and their ratings on Flipkart:"""

figure = px.scatter(data_frame = data, x="Number Of Ratings",
                    y="Sale Price", size="Discount Percentage",
                    trendline="ols",
                    title="Relationship between Sale Price and Number of Ratings of iPhones")
figure.show()

"""There is a negative linear relationship between the sale price of iPhones and the number of ratings. It means iPhones with lower sale prices are sold more in India. Now let’s have a look at the relationship between the discount percentage on iPhones on Flipkart and the number of ratings:"""

figure = px.scatter(data_frame = data, x="Number Of Ratings",
                    y="Discount Percentage", size="Sale Price",
                    trendline="ols",
                    title="Relationship between Discount Percentage and Number of Ratings of iPhones")
figure.show()

"""There is a linear relationship between the discount percentage on iPhones on Flipkart and the number of ratings. It means iPhones with high discounts are sold more in India.

# ***Summary***

So this is how you can analyze the sales of iPhones in India using the Python programming language. Some of the takeaways from this article about the sales of iPhone in India are:


*   APPLE iPhone 8 Plus (Gold, 64 GB) was the most appreciated iPhone in India
*   iPhones with lower sale prices are sold more in India
*   iPhones with high discounts are sold more in India
"""